/* Format controls, output estimates, bitrate guidance, and app bootstrap. */
function human(b){const u=["B","KB","MB","GB","TB"];let i=0;while(b>=1024&&i<u.length-1){b/=1024;i++;}return(i>=2?b.toFixed(1):Math.round(b))+" "+u[i];}
function estBytes(it){const dur=it.dur||0;if(!dur)return null;const p=profileFor(it);if(p.mode.startsWith("ProRes")){const fps=it.fps||30,w=it.width||1920,h=it.height||1080;return w*h*5.31*fps*dur/8;}const sourceBytes=it.size||((it.kbps||0)*1000/8*dur);if(p.rate==="Match source")return sourceBytes||null;if(p.rate==="Custom")return((p.target_mbps||12)*1e6+192000)/8*dur;if(p.rate==="Quality (CRF)"&&sourceBytes)return sourceBytes*(p.mode.startsWith("H.264")?1.05:.78);return null;}
function updateAdjustSummary(){const fmt=formatLabel(mode),rt=mode.startsWith("ProRes")?"Codec-managed":({"Match source":"Match source","Quality (CRF)":"Quality","Custom":"Custom bitrate"}[rate]||rate);document.getElementById("adjustSummary").textContent=`— ${fmt} · ${strength} deband · ${rt}`;}
function syncFormatUI(){const prores=mode.startsWith("ProRes");document.getElementById("adjustRate").style.display=prores?"none":"block";document.getElementById("proresRateNote").style.display=prores?"block":"none";document.querySelectorAll(".hevc-only").forEach(el=>el.hidden=prores);document.getElementById("proresSettingsNote").style.display=prores?"block":"none";if(prores)document.getElementById("customRate").style.display="none";updateAdjustSummary();}
function updateEstimate(){updateAdjustSummary();const el=document.getElementById("estimate");if(!queue.length){el.textContent="";return;}if(queue.some(it=>it.loading)){el.textContent="Estimating output — reading video details…";return;}let total=0,unknown=0,quality=0;const formats={};queue.forEach(it=>{const p=profileFor(it),b=estBytes(it),f=formatLabel(p.mode);if(b==null)unknown++;else total+=b;if(!p.mode.startsWith("ProRes")&&p.rate==="Quality (CRF)")quality++;formats[f]=(formats[f]||0)+1;});if(!total){el.textContent=`Estimating output — ${unknown||queue.length} file${(unknown||queue.length)>1?'s':''} still need readable duration or size metadata.`;return;}let text=`Estimated output: ~${human(total)} (${queue.length} file${queue.length>1?'s':''}) · ${Object.entries(formats).map(([f,n])=>`${n} ${f}`).join(", ")}`;if(queue.some(it=>profileFor(it).mode.startsWith("ProRes")))text+=" · ProRes estimate approximate";if(quality)text+=` · ${quality} quality-mode file${quality>1?'s':''} varies with content`;if(unknown)text+=` · ${unknown} without duration info`;el.textContent=text;}
function refMbps(){let m=0;queue.forEach(it=>{if(it.kbps)m=Math.max(m,it.kbps/1000);});return m;}
function drawZones(){const el=document.getElementById("crBitrate"),max=+el.max,v=+el.value,ref=refMbps(),zone=document.getElementById("crZone"),verdict=document.getElementById("crVerdict");if(ref>0){const s=Math.min(100,ref/max*100),s2=Math.min(100,2*ref/max*100);zone.style.background=`linear-gradient(to right,#1a7f37 0 ${s}%,#c98a00 ${s}% ${s2}%,#b42318 ${s2}% 100%)`;verdict.textContent=v<=ref?`Source ≈ ${ref.toFixed(1)} Mbps · at/below source — safe, smallest file.`:v<=2*ref?`Source ≈ ${ref.toFixed(1)} Mbps · good headroom for grading.`:`Source ≈ ${ref.toFixed(1)} Mbps · above ~2× source — diminishing returns (wasted space).`;}else{zone.style.background="var(--chip)";verdict.textContent="Add files to see source-relative guidance.";}}
function updateCustomRate(){const show=!mode.startsWith("ProRes")&&rate==="Custom";document.getElementById("customRate").style.display=show?"block":"none";if(!show)return;const el=document.getElementById("crBitrate");el.value=SETTINGS.target_mbps||12;document.getElementById("crVal").textContent=(+el.value).toFixed(1)+" Mbps";drawZones();}
function debandGuidance(v){if(v<=.012)return{color:"#c98a00",text:"Very gentle — may leave obvious banding behind."};if(v<=.03)return{color:"#1a7f37",text:"Balanced — start here for normal gradient banding."};if(v<=.05)return{color:"#c98a00",text:"Strong — inspect skin, fine texture, and edges before a batch."};return{color:"#b42318",text:"Very strong — likely to soften texture or create an artificial look."};}
function updateCustomDeband(){const wrap=document.getElementById("customDeband"),range=document.getElementById("customDebandRange"),number=document.getElementById("customDebandNumber"),show=strength==="Custom",value=Math.max(.005,Math.min(.08,Number(SETTINGS.thr_custom)||.03));wrap.style.display=show?"block":"none";if(document.activeElement!==range)range.value=value.toFixed(3);if(document.activeElement!==number)number.value=value.toFixed(3);const guide=debandGuidance(value),verdict=document.getElementById("customDebandVerdict");document.getElementById("customDebandZone").style.background="linear-gradient(to right,#c98a00 0 9%,#1a7f37 9% 33%,#c98a00 33% 60%,#b42318 60% 100%)";verdict.textContent=`${value.toFixed(3)} · ${guide.text}`;verdict.style.color=guide.color;}
let crTimer=null;
function setCustomDeband(value){const v=Math.max(.005,Math.min(.08,Number(value)||.03));SETTINGS.thr_custom=v.toFixed(3);updateCustomDeband();clearTimeout(crTimer);crTimer=setTimeout(()=>saveOne({thr_custom:SETTINGS.thr_custom}),250);}
document.getElementById("customDebandRange").addEventListener("input",e=>setCustomDeband(e.target.value));document.getElementById("customDebandNumber").addEventListener("change",e=>setCustomDeband(e.target.value));document.getElementById("crBitrate").addEventListener("input",()=>{const v=+document.getElementById("crBitrate").value;document.getElementById("crVal").textContent=v.toFixed(1)+" Mbps";SETTINGS.target_mbps=v;drawZones();updateEstimate();clearTimeout(crTimer);crTimer=setTimeout(()=>saveOne({target_mbps:v}),300);});
async function saveOne(patch){const current=await j("/api/settings");SETTINGS={...current,...patch};await j("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(SETTINGS)});}
const SLV=[["st_crf",v=>v],["st_dither",v=>v],["st_deband_range",v=>v+" px"]];SLV.forEach(([id,format])=>{const el=document.getElementById(id);if(el)el.addEventListener("input",()=>document.getElementById(id+"_v").textContent=format(el.value));});function syncSlv(){SLV.forEach(([id,format])=>{const el=document.getElementById(id),label=document.getElementById(id+"_v");if(el&&label)label.textContent=format(el.value);});}
const ZONES={st_crf:{min:0,max:51,bands:[{to:11,color:"#b42318",text:"Excessive — huge files, no visible gain below ~16."},{to:23,color:"#1a7f37",text:"Recommended — visually lossless to very high quality."},{to:28,color:"#c98a00",text:"Acceptable — visible compression on some content."},{to:51,color:"#b42318",text:"Too high — visible quality loss for a delivery master."}]},st_deband_range:{min:1,max:64,bands:[{to:8,color:"#c98a00",text:"Narrow — may not fully smooth wide gradients (skies, smoke)."},{to:32,color:"#1a7f37",text:"Recommended — good balance for most footage."},{to:64,color:"#c98a00",text:"Wide — can start softening detail near edges."}]},st_dither:{min:0,max:20,bands:[{to:0,color:"#b42318",text:"Off — banding can reappear once this is re-compressed."},{to:4,color:"#1a7f37",text:"Recommended — subtle, effectively invisible grain."},{to:9,color:"#c98a00",text:"Visible grain on some content."},{to:20,color:"#b42318",text:"Heavy — visibly grainy/noisy output."}]}};
function renderZone(id){const cfg=ZONES[id],el=document.getElementById(id);if(!cfg||!el)return;const v=+el.value,span=cfg.max-cfg.min||1;let stops=[],position=0,active=cfg.bands[cfg.bands.length-1];cfg.bands.forEach(band=>{const percent=Math.max(0,Math.min(100,(band.to-cfg.min)/span*100));stops.push(`${band.color} ${position}% ${percent}%`);position=percent;if(v<=band.to&&active===cfg.bands[cfg.bands.length-1])active=band;});document.getElementById(id+"_zone").style.background=`linear-gradient(to right,${stops.join(",")})`;const hint=document.getElementById(id+"_hint");if(hint){hint.textContent=active.text;hint.style.color=active.color;}}
Object.keys(ZONES).forEach(id=>{const el=document.getElementById(id);if(el)el.addEventListener("input",()=>renderZone(id));});function syncZones(){Object.keys(ZONES).forEach(renderZone);}
function initializeApp(){j("/api/settings").then(s=>{SETTINGS=s;updateExportTarget();syncFormatUI();updateEstimate();updateCustomRate();updateCustomDeband();});loadCustomPresets();restoreQueue();setControls();}
initializeApp();
