/* Global settings, per-video overrides, reports, and conversion history. */
async function openSettings(){
  const s=await j("/api/settings"), preset=document.getElementById("st_preset");
  if(!preset.options.length) ["ultrafast","superfast","veryfast","faster","fast","medium","slow","slower","veryslow"].forEach(v=>preset.add(new Option(v,v)));
  st_dest_mode.value=s.dest_mode; st_dest_dir.value=s.dest_dir; st_suffix.value=s.suffix; st_on_exists.value=s.on_exists; st_audio.value=s.audio||"copy"; st_dual_export.value=String(s.dual_export); st_live_preview.value=String(!!s.live_preview); engineSelect.value=s.engine||"ffmpeg-deband-v1";
  st_crf.value=s.crf; st_preset.value=s.preset; st_deband_range.value=s.deband_range; st_deband_blur.value=String(s.deband_blur); st_dither.value=s.dither; st_deflicker.value=String(s.deflicker); st_max_quality.value=String(s.max_quality); st_denoise.value=s.denoise||"off"; st_two_pass.value=String(s.two_pass);
  syncSlv(); syncZones(); syncFormatUI(); syncAdvancedVisibility(); document.getElementById("mSettings").classList.add("on");
}
async function pickDest(){ const r=await j("/api/pick-folder-path",{method:"POST"}); if(r.folder){ st_dest_dir.value=r.folder; st_dest_mode.value="custom"; } }
async function saveSettings(){
  const body={dest_mode:st_dest_mode.value,dest_dir:st_dest_dir.value.trim(),suffix:st_suffix.value.trim()||"_10bit",on_exists:st_on_exists.value,audio:st_audio.value,dual_export:st_dual_export.value==="true",live_preview:st_live_preview.value==="true",engine:engineSelect.value,crf:+st_crf.value,preset:st_preset.value,deband_range:+st_deband_range.value,deband_blur:st_deband_blur.value==="true",dither:+st_dither.value,thr_custom:SETTINGS.thr_custom||"0.03",target_mbps:+(SETTINGS.target_mbps??12),deflicker:st_deflicker.value==="true",max_quality:st_max_quality.value==="true",denoise:st_denoise.value,two_pass:st_two_pass.value==="true"};
  if(body.dest_mode==="custom"&&!body.dest_dir){ alert("Choose an output folder, or switch back to “Next to each source”."); return; }
  await j("/api/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); SETTINGS=body; updateExportTarget(); updateEstimate(); updateCustomRate(); updateCustomDeband(); closeModal("mSettings"); setStatus("Settings saved.");
}
function syncClipSettings(){
  const custom=clipUseDefaults.value==="false", prores=clipMode.value.startsWith("ProRes");
  document.querySelectorAll("#clipOverrideFields select,#clipOverrideFields input").forEach(el=>el.disabled=!custom); clipRate.disabled=!custom||prores; clipTarget.disabled=!custom||prores||clipRate.value!=="Custom"; clipRateLabel.style.opacity=prores?".5":"1"; clipTargetLabel.style.opacity=(prores||clipRate.value!=="Custom")?".5":"1"; clipTargetWrap.style.opacity=(prores||clipRate.value!=="Custom")?".5":"1"; clipProResNote.style.display=prores?"block":"none";
}
function openClipSettings(i){ const it=queue[i]; if(!it||running) return; clipSettingsIndex=i; const p=profileFor(it); clipSettingsName.textContent=it.name; clipUseDefaults.value=it.override?"false":"true"; clipMode.value=p.mode; clipStrength.value=p.strength; clipRate.value=p.rate; clipTarget.value=p.target_mbps; clipTargetValue.textContent=(+p.target_mbps).toFixed(1)+" Mbps"; syncClipSettings(); document.getElementById("mClipSettings").classList.add("on"); }
function resetClipSettings(){ if(clipSettingsIndex==null) return; queue[clipSettingsIndex].override=null; saveQueueState(); renderQueue(queue); refreshConvert(); closeModal("mClipSettings"); setStatus("This video now uses the global defaults."); }
function saveClipSettings(){
  if(clipSettingsIndex==null) return; const it=queue[clipSettingsIndex];
  if(clipUseDefaults.value==="true"){ it.override=null; setStatus("This video uses the global defaults."); }
  else { it.override={mode:clipMode.value,strength:clipStrength.value,rate:clipMode.value.startsWith("ProRes")?"Quality (CRF)":clipRate.value,target_mbps:+clipTarget.value||12}; setStatus(`Custom settings saved for ${it.name}.`); }
  saveQueueState(); renderQueue(queue); refreshConvert(); closeModal("mClipSettings");
}
async function openReport(){
  const r=await j("/api/report"), body=document.getElementById("reportBody");
  if(!r||!r.time){ body.textContent="No conversions run yet."; document.getElementById("mReport").classList.add("on"); return; }
  const rows=(r.items||[]).map(it=>`<tr><td>${escHtml(it.name)}</td><td class="s-${escHtml(it.status)}">${escHtml(it.status)}</td><td>${escHtml(it.in_size||"—")} → ${escHtml(it.out_size||"—")}</td><td style="font-size:12px;color:var(--muted)">${escHtml(it.profile||"")}${it.profile&&it.info?" · ":""}${escHtml(it.info||"")}<br><span style="font-family:var(--mono);font-size:11px">${escHtml(it.output||"—")}</span></td></tr>`).join("");
  body.innerHTML=`<div class="row-inline" style="margin-bottom:8px;flex-wrap:wrap;gap:16px"><div><b>${escHtml(r.time)}</b></div><div>${r.done} done${r.skipped?`, ${r.skipped} skipped`:""}${r.failed?`, ${r.failed} failed`:""}${r.cancelled?", cancelled":""}</div><div>${escHtml(r.total_in_size||"—")} → ${escHtml(r.total_out_size||"—")}</div><div>${r.elapsed_sec}s</div></div><div class="hint" style="margin-bottom:8px">${r.mode} · ${r.strength} deband · ${r.rate}</div><table style="width:100%;border-collapse:collapse;font-size:13px"><tr style="text-align:left;color:var(--muted)"><th>File</th><th>Status</th><th>Size</th><th>Detail / exact output</th></tr>${rows}</table>`;
  document.getElementById("mReport").classList.add("on");
}
let historyRecords=[];
async function copyPath(text){ try{await navigator.clipboard.writeText(text);setStatus("Path copied.");}catch(_){const el=document.createElement("textarea");el.value=text;document.body.appendChild(el);el.select();document.execCommand("copy");el.remove();setStatus("Path copied.");} }
async function openHistory(){
  const body=document.getElementById("historyBody"); body.textContent="Loading history…"; document.getElementById("mHistory").classList.add("on"); const r=await j("/api/history"); historyRecords=r.reports||[];
  if(!historyRecords.length){body.textContent="No completed conversions yet.";return;}
  body.innerHTML=historyRecords.map((report,ri)=>{const rows=(report.items||[]).map((it,ii)=>`<tr><td>${escHtml(it.name||"")}</td><td class="s-${escHtml(it.status||"")}">${escHtml(it.status||"")}</td><td style="font-family:var(--mono);font-size:11px;word-break:break-all">${escHtml(it.output||"—")}</td><td><button class="mini" onclick="copyPath(historyRecords[${ri}].items[${ii}].output)">Copy path</button>${it.output?` <button class="mini" onclick="revealHistory(${ri},${ii})">Reveal</button>`:""}${it.source?` <button class="mini" onclick="retryHistory(${ri},${ii})">Retry</button>`:""}${it.error?` <button class="mini" onclick="showMsg('Conversion failed',historyRecords[${ri}].items[${ii}].error+'\\n\\n'+(historyRecords[${ri}].items[${ii}].recovery||''))">Why it failed</button>`:""}</td></tr>`).join("");return `<section style="border-top:1px solid var(--line);padding:12px 0"><div class="row-inline" style="justify-content:space-between;gap:10px;flex-wrap:wrap"><b>${escHtml(report.time||"Earlier conversion")}</b><span class="hint" style="margin:0">${escHtml(report.mode||"")} · ${escHtml(report.strength||"")} deband · ${escHtml(report.rate||"")}</span></div><table style="width:100%;border-collapse:collapse;font-size:12px;margin-top:8px"><tr style="text-align:left;color:var(--muted)"><th>File</th><th>Result</th><th>Output</th><th></th></tr>${rows}</table></section>`;}).join("");
}
async function revealHistory(reportIndex,itemIndex){const path=historyRecords[reportIndex]?.items?.[itemIndex]?.output;if(path)await j("/api/reveal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path})});}
async function retryHistory(reportIndex,itemIndex){const item=historyRecords[reportIndex]?.items?.[itemIndex];if(!item?.source)return;const r=await j("/api/restore-queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:[{path:item.source,override:item.override||null,output_suffix:item.output_suffix||""}]})});const restored=r.items?.[0];if(!restored){setStatus("The original source file is no longer available.");return;}if(!queue.some(q=>q.path===restored.path&&(q.output_suffix||"")===(restored.output_suffix||"")))queue.push({...restored,status:"Queued",pct:""});saveQueueState();renderQueue(queue);refreshConvert();closeModal("mHistory");setStatus("Retry added to the queue. Confirm the output plan before converting.");openPreflight();}
async function revealFailureLog(path){if(path)await j("/api/reveal-log",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({path})});}
